# Generated by Django 5.1.5 on 2025-01-19 23:34

import django.db.models.deletion
import gccp_api_rest.helpers
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Contract',
            fields=[
                ('id', models.CharField(auto_created=True, default=gccp_api_rest.helpers.ccp_uuid_generator, help_text='ID autogerado do Contrato de Crédito Pessoal (CCP)', max_length=20, primary_key=True, serialize=False, unique=True)),
                ('issue_date', models.DateField(help_text='Data de emissão do contrato')),
                ('borrower_birth_date', models.DateField(help_text='Data de nascimento do tomador')),
                ('disbursed_amount', models.DecimalField(decimal_places=2, help_text='Valor desembolsado', max_digits=10)),
                ('document_number', models.CharField(help_text='Número de documento do tomador (CPF)', max_length=11)),
                ('country', models.CharField(help_text='País do tomador', max_length=20)),
                ('state', models.CharField(help_text='Estado do tomador', max_length=20)),
                ('city', models.CharField(help_text='Cidade do tomador', max_length=20)),
                ('phone_number', models.CharField(help_text='Número de contato do tomador', max_length=20)),
                ('interest_rate', models.DecimalField(decimal_places=2, help_text='Taxa do contrato', max_digits=5)),
            ],
            options={
                'db_table': 'contracts',
            },
        ),
        migrations.CreateModel(
            name='Installment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('installment_number', models.IntegerField(help_text='Número de ordem da parcela')),
                ('amount', models.DecimalField(decimal_places=2, help_text='Valor da parcela', max_digits=10)),
                ('due_date', models.DateField(help_text='Data de vencimento da parcela')),
                ('contract', models.ForeignKey(help_text='Contrato referente a parcela', on_delete=django.db.models.deletion.CASCADE, related_name='installments', to='gccp_api_rest.contract')),
            ],
            options={
                'db_table': 'installments',
                'ordering': ['contract'],
            },
        ),
    ]
